### ISSUE TITLE
我不知道怎么接线

### ISSUE THREAD

**Issue by hellocourse** [slipperstree/raspled#1]
我有一个16*16 的点阵 ， https://detail.tmall.com/item.htm?spm=a230r.1.14.18.HrLrBu&id=40142242128&cm_id=140105335569ed55e27b&abbucket=15（就是这款），我可以怎么开始测试呢？点阵分阴码和阳码吗？

**Comment by hellocourse** [comment]
如果可以的话，加我的qq505697496，详说，谢谢。

**Comment by hellocourse** [comment]
16X64的点阵的移动怎么控制？？

**Comment by slipperstree** [comment]
程序注释里已经写明了，请仔细看注释。
下面是8根引脚的接法，数字是树莓派gpio口
DI=33
CLK=35
LAT=37
A,B,C=40,38,36
D,G=32,31
